/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.3
 * Generated at: 2025-03-07 15:55:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/components/sidebar.jsp", Long.valueOf(1741362926922L));
    _jspx_dependants.put("/WEB-INF/views/components/emplyee_table.jsp", Long.valueOf(1741358539647L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Admin | Dashboard</title>\r\n");
      out.write("    <script async defer src=\"https://unpkg.com/@tailwindcss/browser@4\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!-- Navigation Toggle -->\r\n");
      out.write("<!-- End Navigation Toggle -->\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<div id=\"hs-sidebar-collapsible-group\" class=\"hs-overlay [--auto-close:lg] lg:block lg:translate-x-0 lg:end-auto lg:bottom-0 w-64\r\n");
      out.write("hs-overlay-open:translate-x-0\r\n");
      out.write("-translate-x-full transition-all duration-300 transform\r\n");
      out.write("h-full\r\n");
      out.write("hidden\r\n");
      out.write("fixed top-0 start-0 bottom-0 z-60\r\n");
      out.write("bg-white border-e border-gray-200 dark:bg-neutral-800 dark:border-neutral-700\" role=\"dialog\" tabindex=\"-1\" aria-label=\"Sidebar\" >\r\n");
      out.write("    <div class=\"relative flex flex-col h-full max-h-full \">\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        <header class=\"p-4 flex justify-between items-center gap-x-2\">\r\n");
      out.write("            <a href=\"dashboard\" class=\"flex-none font-semibold text-xl text-black focus:outline-hidden focus:opacity-80 dark:text-white\" aria-label=\"Brand\">SmartRecruit</a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"lg:hidden -me-2\">\r\n");
      out.write("                <!-- Close Button -->\r\n");
      out.write("                <button type=\"button\" class=\"flex justify-center items-center gap-x-3 size-6 bg-white border border-gray-200 text-sm text-gray-600 hover:bg-gray-100 rounded-full disabled:opacity-50 disabled:pointer-events-none focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:border-neutral-700 dark:text-neutral-400 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:hover:text-neutral-200 dark:focus:text-neutral-200\" data-hs-overlay=\"#hs-sidebar-collapsible-group\">\r\n");
      out.write("                    <svg class=\"shrink-0 size-4\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 6 6 18\"/><path d=\"m6 6 12 12\"/></svg>\r\n");
      out.write("                    <span class=\"sr-only\">Close</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <!-- End Close Button -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Body -->\r\n");
      out.write("        <nav class=\"h-full overflow-y-auto [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-track]:bg-gray-100 [&::-webkit-scrollbar-thumb]:bg-gray-300 dark:[&::-webkit-scrollbar-track]:bg-neutral-700 dark:[&::-webkit-scrollbar-thumb]:bg-neutral-500\">\r\n");
      out.write("            <div class=\"hs-accordion-group pb-0 px-2  w-full flex flex-col flex-wrap\" data-hs-accordion-always-open>\r\n");
      out.write("                <ul class=\"space-y-1\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"dashboard\" class=\"flex items-center gap-x-3.5 py-2 px-2.5 bg-gray-100 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-700 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-white\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            Dashboard\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"profile\" class=\"w-full flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-neutral-200\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            Profile\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"employees\" class=\"w-full flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-neutral-200\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            Employees\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"recruites\" class=\"w-full flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-neutral-200\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" strokeWidth={1.5} stroke=\"currentColor\" className=\"size-6\">\r\n");
      out.write("                                <path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3.75h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Zm0 3h.008v.008h-.008v-.008Z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            Recruiters\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"offers\" class=\"w-full flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-neutral-200\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.25 14.15v4.25c0 1.094-.787 2.036-1.872 2.18-2.087.277-4.216.42-6.378.42s-4.291-.143-6.378-.42c-1.085-.144-1.872-1.086-1.872-2.18v-4.25m16.5 0a2.18 2.18 0 0 0 .75-1.661V8.706c0-1.081-.768-2.015-1.837-2.175a48.114 48.114 0 0 0-3.413-.387m4.5 8.006c-.194.165-.42.295-.673.38A23.978 23.978 0 0 1 12 15.75c-2.648 0-5.195-.429-7.577-1.22a2.016 2.016 0 0 1-.673-.38m0 0A2.18 2.18 0 0 1 3 12.489V8.706c0-1.081.768-2.015 1.837-2.175a48.111 48.111 0 0 1 3.413-.387m7.5 0V5.25A2.25 2.25 0 0 0 13.5 3h-3a2.25 2.25 0 0 0-2.25 2.25v.894m7.5 0a48.667 48.667 0 0 0-7.5 0M12 12.75h.008v.008H12v-.008Z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("\r\n");
      out.write("                            Offers\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"self-end\">\r\n");
      out.write("                        <a href=\"/auth/logout\" class=\"w-full flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-gray-800 rounded-lg hover:bg-gray-100 focus:outline-hidden focus:bg-gray-100 dark:bg-neutral-800 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700 dark:text-neutral-200\">\r\n");
      out.write("                            <svg  xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15M12 9l3 3m0 0-3 3m3-3H2.25\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("\r\n");
      out.write("                            Logout\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End Body -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End Sidebar -->");
      out.write("\r\n");
      out.write("        <div class=\"ml-[300px] mr-[16px] my-[16px]\">\r\n");
      out.write("            <h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Dashboard</h1>\r\n");
      out.write("            <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"bg-white rounded-lg shadow p-6\">\r\n");
      out.write("                    <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                        <div class=\"bg-blue-50 text-blue-600 p-3 rounded-full\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"text-sm font-medium text-gray-500\">Employees</h3>\r\n");
      out.write("                    <p class=\"text-2xl font-semibold text-gray-900 mt-1\">10</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-white rounded-lg shadow p-6\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <div class=\"bg-green-50 text-green-600 p-3 rounded-full\">\r\n");
      out.write("                                <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"text-sm font-medium text-gray-500\">Recruiters</h3>\r\n");
      out.write("                        <p class=\"text-2xl font-semibold text-gray-900 mt-1\">10</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"bg-white rounded-lg shadow p-6\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <div class=\"bg-orange-50 text-orange-600 p-3 rounded-full\">\r\n");
      out.write("                                <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"text-sm font-medium text-gray-500\">Offers</h3>\r\n");
      out.write("                        <p class=\"text-2xl font-semibold text-gray-900 mt-1\">10</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"bg-white rounded-lg shadow p-6\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <div class=\"bg-purple-50 text-purple-600 p-3 rounded-full\">\r\n");
      out.write("                                <svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3 class=\"text-sm font-medium text-gray-500\">Enrollments</h3>\r\n");
      out.write("                        <p class=\"text-2xl font-semibold text-gray-900 mt-1\">10</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<div class=\"bg-white rounded-lg shadow mb-8\">\r\n");
      out.write("    <div class=\"px-6 py-4 border-b border-gray-200\">\r\n");
      out.write("        <h2 class=\"text-lg font-semibold text-gray-900\">Team Members</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"overflow-x-auto\">\r\n");
      out.write("        <table class=\"min-w-full divide-y divide-gray-200\">\r\n");
      out.write("            <thead class=\"bg-gray-50\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">User</th>\r\n");
      out.write("                <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Role</th>\r\n");
      out.write("                <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Status</th>\r\n");
      out.write("                <th class=\"px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">Location</th>\r\n");
      out.write("                <th class=\"relative px-6 py-3\">\r\n");
      out.write("                    <span class=\"sr-only\">Actions</span>\r\n");
      out.write("                </th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody class=\"bg-white divide-y divide-gray-200\">\r\n");
      out.write("            \r\n");
      out.write("            <tr  class=\"hover:bg-gray-50 transition-colors\">\r\n");
      out.write("                <td class=\"px-6 py-4 whitespace-nowrap\">\r\n");
      out.write("                    <div class=\"flex items-center\">\r\n");
      out.write("                        <div class=\"h-10 w-10 flex-shrink-0\">\r\n");
      out.write("                            <img class=\"h-10 w-10 rounded-full object-cover\"  alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ml-4\">\r\n");
      out.write("                            <div class=\"text-sm font-medium text-gray-900\">Younes ELbasiri</div>\r\n");
      out.write("                            <div class=\"text-sm text-gray-500\">youness@gmail.com</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"px-6 py-4 whitespace-nowrap\">\r\n");
      out.write("                    <div class=\"flex items-center\">\r\n");
      out.write("\r\n");
      out.write("                        <svg class=\"h-4 w-4 text-purple-500 mr-2\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M20.618 5.984A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016zM12 9v3m0 0v3m0-3h3m-3 0H9\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"text-sm 'text-purple-600\">Admin</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"px-6 py-4 whitespace-nowrap\">\r\n");
      out.write("                      <span class=\"px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800\"}>\r\n");
      out.write("                        Active\r\n");
      out.write("                      </span>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <td class=\"px-6 py-4 whitespace-nowrap\">\r\n");
      out.write("                    <div class=\"flex items-center\">\r\n");
      out.write("                        <svg class=\"h-4 w-4 text-gray-400 mr-2\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z\" />\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width={2} d=\"M15 11a3 3 0 11-6 0 3 3 0 016 0z\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                        <span class=\"text-sm text-gray-500\">Casablanca</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"px-6 py-4 whitespace-nowrap text-right text-sm font-medium\">\r\n");
      out.write("                    <a>Delete</a>\r\n");
      out.write("                    <a>Edit</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
